# @package suite
defaults:
  - _self_
  - task: aloha_env
  - /suite@points_cfg: points_cfg

suite: aloha_env
name: "aloha_env"

# Path to the YAML file with ego->robot transform. Override this per robot setup.
T_ego_to_robot_yaml: ???

# obs dims
img_size: [720, 960]  # width, height
use_robot_points: false
num_robot_points: null
gt_depth: true

# action compute
point_dim: 3
action_type: "absolute" # absolute, delta

# object points
use_object_points: true
num_object_points: ${suite.task.num_object_points}

# task settings
action_repeat: 1
hidden_dim: 512

# train settings
num_train_steps: 400010
log_every_steps: 100
save_every_steps: 50000
history: false
history_len: 10

# eval
eval_every_steps: 200000
num_eval_episodes: 1
eval_history_len: 10

# data loading
action_after_steps: 1

# obs_keys
pixel_keys: ["pixels6"]
proprio_key: ""
feature_key: "features"

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.p3po.make
  task_name: ${suite.task.task_name}
  object_labels: ${suite.task.object_labels}
  root_dir: ${suite.task.root_dir}
  action_repeat: ${suite.action_repeat}
  height: ${suite.img_size[1]}
  width: ${suite.img_size[0]}
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
  calib_path: ${root_dir}/calib/0331_calib_left_demo_7.npy
  eval: ${eval} # eval true mean use robot
  pixel_keys: ${suite.pixel_keys}
  use_robot_points: ${suite.use_robot_points}
  num_robot_points: ${suite.num_robot_points}
  use_object_points: ${suite.use_object_points}
  num_object_points: ${suite.num_object_points}
  action_type: ${suite.action_type}
  points_cfg: ??? # to be specified later
  use_gt_depth: ${suite.gt_depth}
  point_dim: ${suite.point_dim}
  prompts: ${suite.task.prompts}
